tasks:
  - name: Start Rocket.Chat
    init: |
      curl https://install.meteor.com/?release=$(curl -so- https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/apps/meteor/.meteor/release | cut -d@ -f2) | sh
      export PATH=$PATH:/home/gitpod/.meteor
      export ROOT_URL=$(gp url 3000)
      nvm install v14.19.3
      nvm use v14.19.3
      yarn
      yarn build
    command: |
      export PATH=$PATH:/home/gitpod/.meteor
      export ROOT_URL=$(gp url 3000)
      nvm use v14.19.3 && yarn dev

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

vscode:
  extensions:
    - esbenp.prettier-vscode
    - eslint