tasks:
  - name: Start Rocket.Chat
    env:
      PATH: $PATH:/home/gitpod/.meteor
      ROOT_URL: $(gp url 3000)
    init: |
      yarn
      yarn build
    command: |
      yarn dev

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

ports:
  - port: 3001
    onOpen: ignore
    name: mongo-db
    visibility: public
  - port: 3000
    onOpen: ignore
    name: rc-server
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - akosyakov.gitpod-monitor
