tasks:
  - name: Start Rocket.Chat
    before:
      eval $(gp env -e PATH=$PATH:/home/gitpod/.meteor)
      eval $(gp env -e ROOT_URL=$(gp url 3000))
    init: |
      yarn
      yarn build
    command: |
      yarn dev

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

ports:
  - port: 3001
    onOpen: ignore
    name: mongo-db
    visibility: public
  - port: 3000
    onOpen: ignore
    name: rc-server
    visibility: public

image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - akosyakov.gitpod-monitor
